// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROhrRhXJmVIQZ2d7FyLVKBtj8DODMsPM',
    appId: '1:319387978914:web:9bb04f27b8095963899bfb',
    messagingSenderId: '319387978914',
    projectId: 'sweetbite-2c88e',
    authDomain: 'sweetbite-2c88e.firebaseapp.com',
    storageBucket: 'sweetbite-2c88e.firebasestorage.app',
    measurementId: 'G-FX1LCMMCQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK4qi7BNN9JKmIy-4tpRcoFdzsX5tNbK0',
    appId: '1:319387978914:android:ae1988fe069b089b899bfb',
    messagingSenderId: '319387978914',
    projectId: 'sweetbite-2c88e',
    storageBucket: 'sweetbite-2c88e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCROhrRhXJmVIQZ2d7FyLVKBtj8DODMsPM',
    appId: '1:319387978914:web:c8c5a1c1bf9f8ce3899bfb',
    messagingSenderId: '319387978914',
    projectId: 'sweetbite-2c88e',
    authDomain: 'sweetbite-2c88e.firebaseapp.com',
    storageBucket: 'sweetbite-2c88e.firebasestorage.app',
    measurementId: 'G-W20K8BP697',
  );
}
